String pattern requires Rust 1.82+
    error[E0005]: refutable pattern in local binding
       --> tests/test.rs:195:9
        |
    195 |     let MustBe!("string") = MustBe!("string");
        |         ^^^^^^^^^^^^^^^^^ pattern `monostate::string::MustBeStr::__Phantom(_)` not covered
        |
        = note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant
        = note: for more information, visit https://doc.rust-lang.org/book/ch18-02-refutability.html
        = note: the matched value is of type `monostate::string::MustBeStr<(len<6>, (monostate::alphabet::char<'s'>, monostate::alphabet::char<'t'>, monostate::alphabet::char<'r'>, monostate::alphabet::char<'i'>, monostate::alphabet::char<'n'>, monostate::alphabet::char<'g'>))>`
        = note: this error originates in the macro `MustBe` (in Nightly builds, run with -Z macro-backtrace for more info)
    help: you might want to use `if let` to ignore the variant that isn't matched
        |
    195 |     if let MustBe!("string") = MustBe!("string") { todo!() };
        |     ++                                           +++++++++++