Raise required compiler to rust 1.60
On older ones, cargo fails like this:

    error: failed to select a version for the requirement `syn = "^2.0.59"`
    candidate versions found which didn't match: 2.0.56, 2.0.55, 2.0.54, ...
    location searched: crates.io index
    required by package `monostate-impl v0.1.12`